In [1]:
import pandas as pd
import numpy as np


In [ ]:
#myarr = np.array([3,6,32,7])
myarr = np.array([3,6,32,6], np.int64) # one dimension

In [6]:
myarr[2]

32

In [7]:
myarr = np.array([[3,6,32,6]], np.int64) #2-d


In [9]:
myarr.shape

(1, 4)

In [10]:
myarr[0,1]

6

In [11]:
# for changing element 
myarr[0,1] = 45

In [12]:
myarr

array([[ 3, 45, 32,  6]], dtype=int64)

# Array Creation : Conversion from other python structure

In [13]:
listarray = np.array([[1,2,3],[5,8,4],[0,6,7]]) 

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 4],
       [0, 6, 7]])

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray[1,1]

8

In [17]:
listarray.size

9

In [18]:
zeros = np.zeros((2,5)) #creating 2 rows , 5 coloums with zero element

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros[1,2]

0.0

In [ ]:
rng = np.arange(17) # create a array of 1 t0 16

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
# create a array of equal space from 1 to 50 within in equal space
lspace = np.linspace(1,50,10)

In [25]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
emp = np.empty((4,6)) # random values

In [27]:
emp

array([[4.24048279e+175, 9.42861792e-143, 7.79355884e-143,
        9.18187358e+170, 7.35958394e+223, 1.82232320e-086],
       [3.67589462e+228, 1.04918902e-153, 4.30899964e-096,
        5.50413877e-143, 3.81695151e+180, 2.59027907e-144],
       [1.04918677e-153, 4.74838007e+170, 4.32359778e-096,
        1.11460097e+171, 4.76441924e+233, 1.04917936e-153],
       [1.04617322e-142, 8.45107192e+252, 5.24022353e+257,
        1.82232320e-086, 5.50412292e-143, 5.26992566e+170]])

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
ide = np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
# reshape, ravel
arr = np.arange(56)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [35]:
arr.reshape(4,14)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]])

In [40]:
arr.shape

(56,)

In [38]:
arr= arr.ravel()

In [39]:
arr.shape

(56,)

#numpy axis#
--------------------
*1* *d* = *0* *axis* 
-----------------------
*2 d = 0 axis for columns, 1 axis for rows*
------------------------------------------
by using sum(axis = 0) we get sum of each columns


In [41]:
x = [[1,2,3],[4,5,6],[6,7,8]]

In [42]:
ar = np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
ar.sum(axis = 0) # sum of each columns because of using axis = 0

array([11, 14, 17])

In [45]:
ar.sum(axis = 1)

array([ 6, 15, 21])

In [46]:
# tranpose
ar.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [47]:
ar.flat

In [48]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
6
7
8


In [49]:
ar.ndim

2

In [50]:
ar.size

9

In [ ]:
ar.nbytes #total bits consumed by array

36

In [52]:
one = np.array([1,3,4,657,2])

In [53]:
one.argmax()

3

In [54]:
one.argmin()

0

In [55]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [57]:
ar.argmin()

0

In [58]:
ar.argmax()

8

In [59]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [60]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [61]:
# mathematical function
ar2 = np.array([[1,2,3],[4,5,7],[9,8,6]])

In [62]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 13],
       [15, 15, 14]])

In [63]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 42],
       [54, 56, 48]])

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 2.64575131, 2.82842712]])

In [65]:
ar.sum()

42

In [66]:
ar.max()

8

In [67]:
ar.min()

1

In [68]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [69]:
np.count_nonzero(ar)

9

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [71]:
ar[1,2] = 0


In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [73]:
import sys

In [75]:
py_ar = [0 ,4,55,2]

In [76]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1) * len(py_ar)

112

In [78]:
np_ar.itemsize * np_ar.size

16