In [6]:
pip install PyTorch

  Using cached pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for PyTorch
Failed to build PyTorch
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\star\AppData\Local\Temp\pip-install-g697x644\pytorch_37da94e9322041759be30faf25edfc97\setup.py", line 15, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyTorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyTorch)


In [10]:
%pip install torch

import torch

Note: you may need to restart the kernel to use updated packages.


In [13]:
torch.rand(2,4)

tensor([[0.1505, 0.4072, 0.5056, 0.8565],
        [0.4235, 0.9714, 0.9773, 0.5402]])

In [14]:
x = torch.empty(4,5)

In [15]:
x

tensor([[8.3842e+03, 2.0501e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
arr = torch.tensor([[1, 3, 4], [4, 5, 3], [5, 8, 9]])


In [17]:
arr

tensor([[1, 3, 4],
        [4, 5, 3],
        [5, 8, 9]])

In [18]:
arr.shape

torch.Size([3, 3])

In [26]:
x = torch.empty(2,4)

In [27]:
x

tensor([[8.1979e+03, 2.0501e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.empty(2,2,3) # 3 d 

tensor([[[8.5121e+03, 2.0501e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])